# Generated by Django 4.2.1 on 2023-05-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucherdate", models.DateField(null=True)),
                (
                    "voucheramount",
                    models.DecimalField(decimal_places=2, max_digits=16, null=True),
                ),
                ("paid_to", models.CharField(max_length=255)),
                ("debitcredit", models.CharField(max_length=15)),
                ("bankorcash", models.CharField(max_length=15)),
                ("narration1", models.CharField(max_length=255)),
                ("narration2", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="fees_balance",
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fees_paid",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fees_paid_date",
            field=models.DateField(null=True),
        ),
    ]
