# Generated by Django 4.2.1 on 2023-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_voucher_member_fees_balance_member_fees_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=255)),
            ],
        ),
    ]
